taco:
  orders:
    pageSize: 10

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword

  profiles:
    active:
      - prod
      - audit
      - ha

logging:
  level:
    root: WARN
    tacos: DEBUG
    org:
      springframework:
        security: DEBUG
  path: $HOME/doko/Downloads/
  file: TacoCloud.log

greeting:
  welcome: ${spring.application.name}