server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
  path: $HOME/doko/Downloads/
  file: TacoCloud.log
